config/routes.rb
Aboutjerseycity::Application.routes.draw do
  
  root :to => 'pages#index'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :projects

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :url, :image

  validates :description, :title, :url, presence: true
  validates :user_id, presence: true
  validates_attachment :image, #presence: :true, 
  						content_type: {content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
  						size: {less_than: 5.megabytes}

  belongs_to :user
  has_attached_file :image, styles: {medium: "400x300>"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :mailchimp

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :projects, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.projects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_footer.html.slim
footer.row
	div class="large-12 columns"
		hr
		.row
			div class="large-6 columns"
				p <strong>About Jersey City</strong> was crafted with &hearts; by Ciara Burkett, a Rails Developer and web designer.
			div class="large-6 columns"
				ul class="inline-list right"
					li
						a href="http://www.twitter.com/aboutjerseycity" target="_blank"
							i class="icon-twitter"
					li
						a href="http://www.facebook.com/aboutjerseycity" target="_blank"
							i class="icon-facebook"
					li
						a href="http://www.linkedin.com/in/ciaraburkett" target="_blank"
							i class="icon-linkedin"
					li
						a href="http://www.github.com/CiaraBurkett/aboutjerseycity" target="_blank"
							i class="icon-github"
					li
						a href="/contact"
							i class="icon-phone"

app/views/layouts/_header.html.slim
nav class="top-bar"
	ul class="title-area"
		li.name
			h1 
				|<a href="/"><i class="icon-map-marker"></i> About Jersey City<sup>alpha</sup></a>
		li class="toggle-topbar menu-icon"
			a href="#"
				span Menu
	section class="top-bar-section"
		ul.left
			li
				= link_to "Home", root_path
			li
				= link_to "About", about_path
			li
				= link_to "Blog", "http://www.aboutjerseycity.tumblr.com", :target => "_blank"
			li
				= link_to "Contact", contact_path
		ul.right
			- if user_signed_in?
				li
					= link_to "Add +", new_project_path
				li
					= link_to "Projects", projects_path
				li
					= link_to "Edit Profile", edit_user_registration_path
				li
					= link_to "Logout", destroy_user_session_path, method: :delete
				li.divider
			- else
				li
					= link_to "List Projects", projects_path
				li
					= link_to "Login", new_user_session_path
				li.divider

.container
	/ header.row
	/ 	div class="large-4 columns"
	/ 	div class="large-8 columns"

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"

  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  title= content_for?(:title) ? yield(:title) : "About Jersey City, a local directory"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

  / Typekit Pragmatica Web
  script type="text/javascript" src="//use.typekit.net/dyp4dqw.js"
  script type="text/javascript" try{Typekit.load();}catch(e){}

  / Google Web Fonts Roboto Slab
  link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,100,300' rel='stylesheet' type='text/css'

  / ShareThis Button
  script type="text/javascript" var switchTo5x=true;
  script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"
  script type="text/javascript" stLight.options({publisher: "407ebe12-f168-489b-b890-9b15784a5928", doNotHash: false, doNotCopy: false, hashAddressBar: true});

  / Google Analytics
  = analytics_init if Rails.env.production?
body

	== render 'layouts/header'
  
	- flash.each do |name, msg|
    	.row
      		div class="large-12 columns"
        		div data-alert="" class="alert-box radius"
          			= content_tag(:div, msg, class: "alert alert-#{name}")
          			a href="#" class="close" &times;

	== yield

	== render 'layouts/footer'

	= javascript_include_tag "application"

app/views/pages/about.html.slim
.row
	div class="large-4 columns"
		div class="panel radius"
			h3 Who?
			p Hello!  I'm <strong>Ciara Burkett</strong>, and I made About Jersey City.  I'm a local Rails developer, web designer, and entrepreneur.  
			p In my spare time, I organize the <a href="http://www.meetup.com/JerseyCityrb" target="_blank">JerseyCity.rb</a> Ruby learning group and <a href="http://www.meetup.com/AboutJerseyCity" target="_blank">About Jersey City</a>, an entrepreneur networking and collaboration group named after the project.
			p Got an idea for an app?
			center
				= link_to "Contact Me!", contact_path, :class => "radius button"

	div class="large-8 columns"
		h2 What?
		p About Jersey City is a directory of local projects.  This can be anything from a weekly event, a non-profit organization, a business, an idea, or a reading group.
		p Are you doing something cool and you want more people to know about it?
		= link_to "Sign up!", new_user_registration_path, :class => "radius button"

		h2 When?
		p The alpha release of About Jersey City was launched June 2013.  Sporadic changes in web copy and small bug fixes will occur occasionally, but the next major release is estimated to launch September 2013.

		h2 Where?
		p Jersey City, of course!
		p I've been planning, designing, and coding About Jersey City in my home office and various cafes around town.

		h2 Why?
		p For two reasons:
		ol
			li It's exceedingly difficult for someone on a tiny budget to promote their work without being plugged into social media 24/7.
			li As far as I know, there really isn't a central place to just browse local projects of all kinds.  (Well, there is now!) 

.row
	div class="large-12 columns"
		div class="panel radius"
			h4 How?
			.row
				div class="large-9 columns"
					p I'm so glad you asked!  I made About Jersey City using Ruby on Rails, a web application framework great for saving time and money on projects.  Looking for a developer to help you bring your ideas to life?
				div class="large-3 columns"
					= link_to "Get in touch!", contact_path, :class => "radius button right"

app/views/pages/contact.html.slim
.row
	div class="large-12 columns"
		h1 Get in touch!
.row
	div class="large-8 columns"
		p For general feedback, email me at <strong>ciara@aboutjerseycity.com</strong>.
		p To submit ideas for new features, head on over to the <a href="http://www.aboutjerseycity.uservoice.com" target="_blank">Support Forums</a> where you can add and vote on suggestions.
	div class="large-4 columns"
		div class="panel radius"
			p For development work, shoot me an email at <strong>ciaraburkett@gmail.com</strong> for an initial consultation.

app/views/pages/index.html.slim
.row
	div class="large-8 columns"
		- if user_signed_in?
			div class="panel radius"
				h2 Dashboard
				/ Use Analytics.js and D3.js (with CoffeeScript?) to create dynamic infographic
				/ h3 My Projects
				iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src="http://forecast.io/embed/#lat=40.6916&lon=-74.0923&name=Jersey City"

				h3 More features coming soon!
				p Projest listings, analytics, and more coming in the beta release!  If you have any ideas for new features you think would make About Jersey City even better, feel free to tell me about it!
				= link_to "Support Forums", "http://www.aboutjerseycity.uservoice.com", :target => "_blank"
		- else
			div class="panel radius"
				h2 Welcome!
				p About Jersey City is an online directory of creative and entrepreneurial projects born and raised in Jersey City.  We help people spread the word around town!
				p Want to see your project listed in our directory?
				= link_to "Sign up!", new_user_registration_path, :class => "radius button"
	div class="large-4 columns"
		h3 Sponsors
		a href="/contact"
			img src="http://placehold.it/400x300&text=Your Ad Here"

		- if user_signed_in?
			h3 Latest News
			a class="twitter-timeline" href="https://twitter.com/aboutjerseycity" data-widget-id="354718874823958528" Tweets by @aboutjerseycity

			script !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/projects/_form.html.slim
.row
  div class="large-12 columns"
    = form_for @project do |f|
      - if @project.errors.any?
        #error_explanation
          h3 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
          ul
            - @project.errors.full_messages.each do |message|
              li = message

      .field
        = f.label :title
        = f.text_field :title, :placeholder => "My Project Title"
      .field
        = f.label :url
        = f.text_field :url, :placeholder => "http://www.example.com"
      .field
        = f.label :description
        = f.text_field :description, :placeholder => "Please limit your description to less than five sentences."
      .field
        = f.label :image
        = f.file_field :image
      br
      .actions = f.submit 'Save', :class => "small radius button"

app/views/projects/_project.html.slim
h4
	dt = link_to project.title, project
dd = project.description
hr
ul
	li
		i class="icon-plus"
	li
		= link_to 'View', project
	- if current_user == project.user
		li
			= link_to 'Edit', edit_project_path(project)
		li
			= link_to 'Delete', project, :confirm => 'Are you sure?  Deleting a project CANNOT be reversed.', :method => :delete

app/views/projects/edit.html.slim
.row
  div class="large-8 columns"
    h2 Editing Project

    == render 'form'
    ul class="inline-list right"
	    li
	      = link_to 'View', @project
	    li
	      = link_to 'Back to Projects', projects_path

app/views/projects/index.html.slim
.row
  div class="large-8 columns"
    h2 Projects

    dl
      == render @projects
    br
    - if user_signed_in?
      = link_to 'New Project', new_project_path

app/views/projects/new.html.slim
.row
  div class="large-8 columns"
    h2 New Project

    == render 'form'

    = link_to 'Back to Projects', projects_path

app/views/projects/show.html.slim
.row
  div class="large-8 columns"
    div class="panel radius"
      h2 = @project.title
      p 
        h3 = link_to @project.url, @project.url, :target => "_blank"
      p = @project.description
      p
        em by:  
        = @project.user.name

      span class='st_sharethis_large' displayText='ShareThis'
      span class='st_facebook_large' displayText='Facebook'
      span class='st_twitter_large' displayText='Tweet'
      span class='st_tumblr_large' displayText='Tumblr'
      span class='st_linkedin_large' displayText='LinkedIn'
      span class='st_pinterest_large' displayText='Pinterest'
      span class='st_email_large' displayText='Email'

    ul class="inline-list right"
      - if current_user == @project.user
        li
          = link_to 'Edit', edit_project_path(@project)
      li
        = link_to 'Back to Projects', projects_path

  div class="large-4 columns"
    div class="panel radius"
      = image_tag @project.image, :alt => "This project doesn't have an image yet!"